from enum import Enum

class GameState(Enum):
    ATTRACT = 0
    INITIAL = 1
    YOUR_NAME = 2
    NICE_NAME = 4
    PRESS_5 = 5
    HAVE_LUCK = 6
    INSTRUCTIONS = 7
    PLAYING_HUGO = 8
    GOING_SCYLLA = 9
    PLAYING_SCYLLA_0 = 10
    PLAYING_SCYLLA_1_BAD = 11
    PLAYING_SCYLLA_1_GOOD = 12
    PLAYING_SCYLLA_1_BEST = 13
    PLAYING_SCYLLA_2_BAD = 14
    PLAYING_SCYLLA_2_GOOD = 15
    PLAYING_SCYLLA_2_BEST = 16
    PLAYING_SCYLLA_3_BAD = 17
    PLAYING_SCYLLA_3_GOOD = 18
    PLAYING_SCYLLA_3_BEST = 19
    ENDING = 20